on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight. Adjust the timing as needed.

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/LeDragoX/Win-Debloat-Tools

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Rebase upstream/main
        run: git rebase upstream/main

      - name: Push changes
        run: git push origin main --force
